FROM golang:1.19-alpine as builder

ENV APP_HOME=/usr/src/app

WORKDIR ${APP_HOME}

# pre-copy/cache go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY bot.go .env ./
RUN CGO_ENABLED=0 go build -ldflags="-s -w" -v -o app

# production build
FROM scratch

ENV APP_HOME=/usr/src/app

WORKDIR ${APP_HOME}
COPY --from=builder "$APP_HOME"/app $APP_HOME

EXPOSE 8080

CMD ["app"]